### PR TITLE
N°5995 - Fix PHP warning on lookup when table is empty

### PR DESCRIPTION
**Pull request by accognet**
Avoid the message :
PHP Warning: Invalid argument supplied for foreach() in .... core/lookuptable.class.inc.php on line 59
when the requested table is empty

### CODE REVIEW

**Comment by Hipska** [comment]
Could also just have done `foreach ((array)$aRes['objects'] as $sObjKey => $aObj)`

**Comment by Molkobain** [comment]
Indeed the fix proposed by Thomas would be nicer as it avoids the extra indentation. I'm in favor for it as well.

Also, your formatter changed the brackets position to something not in the convention. Please revert these and check the changes in your IDE before committing.

**Review by Hipska — APPROVED** [review]

**Review by xtophe38 — APPROVED** [review]
Tested on Azure collector. Works fine.

**Comment by Molkobain** [comment]
Fine by me as well, you can
  * Squash & merge the PR
  * Resolve the corresponding ticket
  * Update the changelogs of the base, LDAP and vSphere collectors

**Pull request merged**
