### PR TITLE
N°5067 - Cleanup RestClient::GetFullSynchroDataSource()

### PR DESCRIPTION
**Pull request by Hipska**
Remove some extra fields that are not needed

### CODE REVIEW

**Comment by Hipska** [comment]
Yes, there is no bug, but its indeed reducing output, which also reduces the number of (useless) fields that are compared when syncing SDS settings..

**Comment by piRGoif** [comment]
Ok thanks !
Setting this PR to be reviewed

**Comment by piRGoif** [comment]
Sorry, we missed technical review today (too much PR to review). Will be reviewed next month !

**Comment by Molkobain** [comment]
Accepted in technical review.
Will see next week if product team can test this on their own.

**Comment by Molkobain** [comment]
Accepted in functional review, will part of the next collectors releases (no planned date)

**Pull request merged**
