### PR TITLE
Add missing default config parameters

### PR DESCRIPTION
**Pull request by Hipska**
These config parameters were missing from the sample config file.

See also https://github.com/TeemIp/teemip-ip-discovery-collector/pull/3#pullrequestreview-1561135596

### CODE REVIEW

**Review by piRGoif — APPROVED** [review]

**Review by xtophe38 — APPROVED** [review]

**Review by accognet — APPROVED** [review]

**Comment by Hipska** [comment]
Whoops, that was a mistake in my git client, I thought it was already merged..

**Comment by piRGoif** [comment]
Ok thanks :)

**Comment by piRGoif** [comment]
Technical review : OK !

**Comment by piRGoif** [comment]
Functional review : OK

**Pull request merged**
