### PR TITLE
N°5709 - Fix warning when aSkippedAttributes is not correctly populated

### PR DESCRIPTION
**Pull request by Hipska**
The array was only populated on initial run (when data synchro needs to be created) or when synchro needs to be updated.

Better way is to use the method intended for this use.

Note that jsoncollector and SQLCollector are also using this array, it might be that those need an update as well..

### CODE REVIEW

**Comment by Hipska** [comment]
@piRGoif Any feedback?

**Comment by piRGoif** [comment]
Hello Thomas, 
I'm not assigned to this PR so I can't answer.
The "first review needed" state means a Combodo dev need to take a look and do a first review. When ready he/she will present the PR to the rest of the dev team, and/or to the product team.
For now I don't have any resource to take a PR or two, and I still got some that are in progress.
We are a little late on processing the PR flow those last weeks, I hope we will catch up.

**Comment by Hipska** [comment]
Okay thanks, but this one is from March, not just the last few weeks 😂

**Comment by piRGoif** [comment]
You're right :/
Sorry...

**Comment by Hipska** [comment]
@piRGoif I know you aren't assigned (nobody seems to be), but could you give an update please?

Almost 1 year without feedback, so I don't know if this is a potential good PR or I just discard my hopes of it getting merged.

**Comment by piRGoif** [comment]
Hello,

We are now reviewing PR on a regular basis (a review every month), but we have some work to catch up...

There are currently 9 old PR that are waiting for a developer assignee - it ain't much (compared to the 51 community PR we handled last year), but it will take us a few weeks to get to 0, or at least process the old PRs.

The PR review progress can be monitored in our org project : https://github.com/orgs/Combodo/projects/2

**Comment by Molkobain** [comment]
Hello Thomas, I'll check this PR on friday, would you update/rebase you branch on master in the meantime? Thanks

**Comment by Hipska** [comment]
Erm, it is already on master and there are no conflicts in between..

**Comment by Hipska** [comment]
@Molkobain any update please?

**Comment by piRGoif** [comment]
Hello,
We still have multiples PR from 2020 and 2021 to catch up like this one... Sorry we're definitively late and have a hard time closing the gap... I hope we'll be able to get to it in the coming monthes.

**Comment by Hipska** [comment]
I just want to know if it is okay or not:

> Almost 1 year without feedback, so I don't know if this is a potential good PR or I just discard my hopes of it getting merged.

**Comment by xtophe38** [comment]
As @Hipska mentionned at the beginning of the PR, array _aSkippedAttributes_ is populated with the output of _AttributeIsOptional_ when (1) a SDS (Synchro Data Source) needs to be created or (2) updated but **not** (3) otherwise. Consequence is that _AddHeader_ will fail with optional attributes in case (3).

Hence @Hipska proposal to rely on _AttributeIsOptional_  instead of _aSkippedAttributes_  within _AddHeader_ ... which I support.

Possible next step: with this PR and the recent https://github.com/Combodo/itop-data-collector-base/pull/16, we should be able to get rid of _aSkippedAttributes_.

**Comment by Molkobain** [comment]
Accepted during functional review.
Technical review will be done in 3 weeks.

@xtophe38 create the corresponding bug in our tracker and update the PR's title please.
He will also test the branch further.

**Comment by Hipska** [comment]
There are still no conflicts..

**Comment by Molkobain** [comment]
> There are still no conflicts..

image

**Comment by Hipska** [comment]
So weird...
image

**Comment by Molkobain** [comment]
We could not do a "rebase and merge", only "squash and merge". Don't really know why. Maybe it's because you merged master into your branch instead of rebasing it? I don't know 😁

**Pull request merged**
