### PR TITLE
 N°5884 - Fix missing attributes in aSkippedAttribute

### PR DESCRIPTION
**Pull request by accognet**
For some classes, array aSkippedAttribute doesn't contain all the fields -> csv created for import contains fields that don't exist in iTop and the import fails.

### CODE REVIEW

**Comment by xtophe38** [comment]
Do you have an easy way to add a PHP Unit test ?

**Review by xtophe38 — COMMENTED** [review]
Reviewed. See comment on Unit Test.

**Comment by odain-cbd** [comment]
Same as Christophe. can you add some tests that cover this case please? does this concern any collector (csv, json, oql)? if so please add a test on each of them?

**Comment by odain-cbd** [comment]
this PR description is hard to understand. this is a technical explanation. not a fonctionnal one.

can you explain when this is happens (which step among data synchro init/collect/synchro itself)? what is the effect? what do you suggest to avoid such an issue?

**Review by odain-cbd — COMMENTED** [review]
code changes are ok to me. a better explanation would be nice to ease the PR review for others...

**Review by odain-cbd — CHANGES_REQUESTED** [review]
code changes are ok to me. a better explanation would be nice to ease the PR review for others...

**Comment by xtophe38** [comment]
Everything is fine for me.

**Comment by piRGoif** [comment]
Thanks for the review ! We can skip the technical review. Setting to be in the next functional review.

**Review by Molkobain — APPROVED** [review]

**Comment by Molkobain** [comment]
Accepted during collector PRs review, you can merge.
Please mind to make a "squash & merge" while keeping the PR number (#xx)

**Pull request merged**
