### PR TITLE
Update csvcollector to manage empty data csv file.

### PR DESCRIPTION
**Pull request by c-dst**
Hi,

The change in csvcollector.class.inc.php manage an empty data csv file, with or without headers.

Regards.

### CODE REVIEW

**Review by Hipska — APPROVED** [review]

**Review by Molkobain — COMMENTED** [review]
Seems good, but if we could have a unit test covering the new use case as well are previous one, it would be way more confortable.

Are you confortable writing a unit test or do you want some hints / help? :)

**Comment by piRGoif** [comment]
Reviewed today with part of the dev team.

Can you detail what is happening without this modification ? I imagine the collector crashes ? 
With your modification, are there any log to inform the user there was an empty file ? 

About adding a phpunit test : we can code it ourselves if you like ? But to do so we would need a write access to your fork branch. To do so, verify the "Allow edits from maintainers" checkbox in this PR ? (see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by Molkobain** [comment]
Accepted during functional review.
Before merging we still need the information asked by Pierre last week, did you have a look @c-dst ?

**Comment by piRGoif** [comment]
Closing this PR, as the work was restarted in #22.

**Pull request closed without merging**
