### PR TITLE
N°5979 - Remove PHP warning and hide test data collectors in iTop setup

### PR DESCRIPTION
**Pull request by Hipska**
2 minor fixes..

- Hide test data collectors as modules in iTop setup
- Remove PHP warning when using an empty mapping table

### CODE REVIEW

**Comment by odain-cbd** [comment]
it is fine by me. but I would even go further in the cleanup...

from my point of view only module files in ./test/getproject are required. because a test rely on them (cf OrchestratorTest).
all the other files are useless and should be cleaned up:
```
/test/single_csv/common/module.test-csvcollector.php
./test/collector/attribute_isnullified/module.test-collector.php
./test/single_json/common/module.data-collector-json.php
```

**Comment by Hipska** [comment]
@odain-cbd done!

**Review by odain-cbd — APPROVED** [review]
good job!

**Review by Molkobain — APPROVED** [review]

**Review by Molkobain — APPROVED** [review]
Accepted during collector PRs review, Guillaume will create the corresponding ticket and merge.

**Pull request merged**
